build_from:
#  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.10-alpine3.16
#  armhf: ghcr.io/home-assistant/armhf-base-python:3.10-alpine3.16
#  armv7: ghcr.io/home-assistant/armv7-base-python:3.10-alpine3.16
#  amd64: ghcr.io/home-assistant/amd64-base-python:3.10-alpine3.16
#  i386: ghcr.io/home-assistant/i386-base-python:3.10-alpine3.16  
  
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:9.0.0
  amd64: ghcr.io/hassio-addons/base-python/amd64:9.0.0
  armhf: ghcr.io/hassio-addons/base-python/armhf:9.0.0
  armv7: ghcr.io/hassio-addons/base-python/armv7:9.0.0
  i386: ghcr.io/hassio-addons/base-python/i386:9.0.0    